import type { NextPage } from 'next'
import Head from 'next/head'
import { useState } from 'react'
import { Uploader } from '../components/Uploader'
import { Wallet } from '../components/Wallet'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const [file, setFile] = useState<File>()

  const content = () => {
    if (file === undefined) {
      return (<Uploader onUploaded={(file) => setFile(file)} />)
    }

    return (<div>uploaded file: {file.name}</div>)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Wallet/>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Mint an NFT
        </h1>


        {content()}
      </main>

      <footer className={styles.footer}>
        Support the developer: BSFtCudCd4pR4LSFqWPjbtXPKSNVbGkc35gRNdnqjMCU
      </footer>
    </div>
  )
}

export default Home
