import type { NextPage } from 'next'
import Head from 'next/head'
import { Uploader } from '../components/Uploader'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Mint an NFT
        </h1>

        <Uploader/>
      </main>

      <footer className={styles.footer}>
        Support the developer: BSFtCudCd4pR4LSFqWPjbtXPKSNVbGkc35gRNdnqjMCU
      </footer>
    </div>
  )
}

export default Home
